services:
  - type: web
    name: altear-video-meeting
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://bevan_admin:bevan_123@lemon0.ybuuqu2.mongodb.net/ashlin?retryWrites=true&w=majority&appName=Lemon0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8181 